/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConnectionDialog: typeof import('./components/ConnectionDialog.vue')['default']
    ConnectionPanel: typeof import('./components/ConnectionPanel.vue')['default']
    DataViewer: typeof import('./components/DataViewer.vue')['default']
    HashViewer: typeof import('./components/HashViewer.vue')['default']
    KeyTree: typeof import('./components/KeyTree.vue')['default']
    ListViewer: typeof import('./components/ListViewer.vue')['default']
    MonitorPanel: typeof import('./components/MonitorPanel.vue')['default']
    NModal: typeof import('naive-ui')['NModal']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetViewer: typeof import('./components/SetViewer.vue')['default']
    StringViewer: typeof import('./components/StringViewer.vue')['default']
    TreeNode: typeof import('./components/TreeNode.vue')['default']
    ZSetViewer: typeof import('./components/ZSetViewer.vue')['default']
  }
}
