// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1:string):Promise<string>;

export function BrowseKeys(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function Connect(arg1:string):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteKey(arg1:string,arg2:string):Promise<number>;

export function Disconnect(arg1:string):Promise<void>;

export function GetConnections():Promise<string>;

export function GetKeyType(arg1:string,arg2:string):Promise<string>;

export function GetMonitorData(arg1:string):Promise<string>;

export function GetRedisVersion(arg1:string):Promise<string>;

export function GetStringValue(arg1:string,arg2:string):Promise<string>;

export function GetTTL(arg1:string,arg2:string):Promise<number>;

export function HashDel(arg1:string,arg2:string,arg3:string):Promise<void>;

export function HashScan(arg1:string,arg2:string,arg3:number,arg4:number,arg5:boolean):Promise<string>;

export function HashSearch(arg1:string,arg2:string,arg3:string):Promise<string>;

export function HashSet(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ListLen(arg1:string,arg2:string):Promise<number>;

export function ListPush(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<number>;

export function ListRange(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function ListRemove(arg1:string,arg2:string,arg3:string,arg4:number):Promise<number>;

export function RenameKey(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ScanKeys(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function SelectDB(arg1:string,arg2:number):Promise<void>;

export function SetAdd(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetMembers(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function SetRemove(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetSearch(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetStringValue(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function SetTTL(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SetWindowTitle(arg1:string):Promise<void>;

export function StartMonitor(arg1:string,arg2:number):Promise<void>;

export function StopMonitor(arg1:string):Promise<void>;

export function TestConnection(arg1:string):Promise<string>;

export function UpdateConnection(arg1:string,arg2:string):Promise<void>;

export function ZSetAdd(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function ZSetRange(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function ZSetRemove(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ZSetScan(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function ZSetSearch(arg1:string,arg2:string,arg3:string):Promise<string>;
