// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1) {
  return window['go']['main']['App']['AddConnection'](arg1);
}

export function BrowseKeys(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BrowseKeys'](arg1, arg2, arg3, arg4);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteKey(arg1, arg2) {
  return window['go']['main']['App']['DeleteKey'](arg1, arg2);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetKeyType(arg1, arg2) {
  return window['go']['main']['App']['GetKeyType'](arg1, arg2);
}

export function GetMonitorData(arg1) {
  return window['go']['main']['App']['GetMonitorData'](arg1);
}

export function GetRedisVersion(arg1) {
  return window['go']['main']['App']['GetRedisVersion'](arg1);
}

export function GetStringValue(arg1, arg2) {
  return window['go']['main']['App']['GetStringValue'](arg1, arg2);
}

export function GetTTL(arg1, arg2) {
  return window['go']['main']['App']['GetTTL'](arg1, arg2);
}

export function HashDel(arg1, arg2, arg3) {
  return window['go']['main']['App']['HashDel'](arg1, arg2, arg3);
}

export function HashScan(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['HashScan'](arg1, arg2, arg3, arg4, arg5);
}

export function HashSearch(arg1, arg2, arg3) {
  return window['go']['main']['App']['HashSearch'](arg1, arg2, arg3);
}

export function HashSet(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['HashSet'](arg1, arg2, arg3, arg4);
}

export function ListLen(arg1, arg2) {
  return window['go']['main']['App']['ListLen'](arg1, arg2);
}

export function ListPush(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListPush'](arg1, arg2, arg3, arg4);
}

export function ListRange(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListRange'](arg1, arg2, arg3, arg4);
}

export function ListRemove(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListRemove'](arg1, arg2, arg3, arg4);
}

export function RenameKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameKey'](arg1, arg2, arg3);
}

export function ScanKeys(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ScanKeys'](arg1, arg2, arg3, arg4);
}

export function SelectDB(arg1, arg2) {
  return window['go']['main']['App']['SelectDB'](arg1, arg2);
}

export function SetAdd(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetAdd'](arg1, arg2, arg3);
}

export function SetMembers(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetMembers'](arg1, arg2, arg3, arg4);
}

export function SetRemove(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetRemove'](arg1, arg2, arg3);
}

export function SetSearch(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSearch'](arg1, arg2, arg3);
}

export function SetStringValue(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetStringValue'](arg1, arg2, arg3, arg4);
}

export function SetTTL(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetTTL'](arg1, arg2, arg3);
}

export function SetWindowTitle(arg1) {
  return window['go']['main']['App']['SetWindowTitle'](arg1);
}

export function StartMonitor(arg1, arg2) {
  return window['go']['main']['App']['StartMonitor'](arg1, arg2);
}

export function StopMonitor(arg1) {
  return window['go']['main']['App']['StopMonitor'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateConnection(arg1, arg2) {
  return window['go']['main']['App']['UpdateConnection'](arg1, arg2);
}

export function ZSetAdd(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ZSetAdd'](arg1, arg2, arg3, arg4);
}

export function ZSetRange(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ZSetRange'](arg1, arg2, arg3, arg4);
}

export function ZSetRemove(arg1, arg2, arg3) {
  return window['go']['main']['App']['ZSetRemove'](arg1, arg2, arg3);
}

export function ZSetScan(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ZSetScan'](arg1, arg2, arg3, arg4);
}

export function ZSetSearch(arg1, arg2, arg3) {
  return window['go']['main']['App']['ZSetSearch'](arg1, arg2, arg3);
}
